using System.Text;
using System.Text.RegularExpressions;

namespace RatNav.Core.Maps;

/// <summary>How much of the map to draw when it is sitting on top of the game.</summary>
public enum MapInkLevel
{
    /// <summary>
    /// The map in its author's own colours, untouched. What a map looks like when you are reading
    /// it rather than glancing at it.
    /// </summary>
    Graphical,

    /// <summary>
    /// Recoloured by what each shape is — structure, boundary, route, hazard — with terrain still
    /// solid underneath. One palette instead of the map's dozen, which is what survives being
    /// drawn over an unpredictable game scene.
    /// </summary>
    Full,

    /// <summary>Terrain drops back to a whisper; buildings, roads and fences carry the map.</summary>
    Structure,

    /// <summary>Outlines only — building edges, roads, and the map border in a single colour.</summary>
    Outline,
}

public sealed record MapInkOptions
{
    public MapInkLevel Level { get; init; } = MapInkLevel.Structure;

    /// <summary>Opacity of the whole map, 0–1. The Diablo-style dial.</summary>
    public double Opacity { get; init; } = 0.55;

    /// <summary>Colour for structure — buildings, walls, fences.</summary>
    public string Accent { get; init; } = "#8ec8ff";

    /// <summary>Colour for the things you navigate by — roads, rail.</summary>
    public string RouteColor { get; init; } = "#e0c98a";

    /// <summary>Faint wash left behind terrain in <see cref="MapInkLevel.Structure"/>.</summary>
    public string TerrainColor { get; init; } = "#9fb3c8";

    public double TerrainOpacity { get; init; } = 0.10;

    /// <summary>Keep the map's own hazard markings. They are worth the pixels.</summary>
    public bool ShowHazards { get; init; } = true;

    /// <summary>
    /// Draw a dark halo behind every line. Tarkov's backgrounds run from snow to unlit
    /// basement, and no single colour is readable against both — a contrasting edge is what
    /// makes one colour work everywhere.
    /// </summary>
    public bool Halo { get; init; } = true;
}

/// <summary>
/// Rewrites a map SVG so it can be laid over the game without drowning it — the translucent
/// dungeon map from Diablo, applied to Tarkov.
///
/// This works by meaning rather than by pixels, which is only possible because the tarkovdata
/// maps carry semantic classes: <c>.building</c>, <c>.trees</c>, <c>.road_tarmac</c>,
/// <c>.fence</c>, <c>.water</c> and friends. So instead of chroma-keying a screenshot of a map
/// and hoping, we replace the stylesheet and say exactly what each kind of thing should look
/// like. It stays sharp at any zoom and there are no keying artefacts, because nothing is
/// being keyed.
/// </summary>
public static partial class MapInk
{
    /// <summary>Terrain: what the ground is made of. Drops away first, since it is the loudest and least useful in a raid.</summary>
    private const string TerrainSelectors = ".trees, .land, .rock, .water, .gravel, .cement, .tarmac, .wood, .misc";

    /// <summary>Structure: what you can walk into, walk on, or not get through.</summary>
    private const string StructureSelectors = ".building, .floor, .locked";

    /// <summary>Lines that bound things — the map edge, fences, thin walls.</summary>
    private const string BoundarySelectors = ".map_border, .fence, .wall";

    /// <summary>The things you actually navigate by.</summary>
    private const string RouteSelectors = ".road_tarmac, .road_gravel, .railroad, .powerline";

    /// <summary>Small detail worth keeping: stairs tell you how to change floor.</summary>
    private const string DetailSelectors = ".stairs, .task, .chopper";

    private const string HazardSelectors = ".danger, .danger_small";

    /// <summary>
    /// Applies an ink level to a map SVG and returns the rewritten markup.
    /// Unrecognised markup is left alone, so a map drawn with classes we don't know about
    /// still renders — it just won't thin out as much.
    /// </summary>
    public static string Apply(string svgMarkup, MapInkOptions options)
    {
        ArgumentNullException.ThrowIfNull(svgMarkup);
        ArgumentNullException.ThrowIfNull(options);

        var markup = svgMarkup;

        // Graphical is the author's own stylesheet, so there is nothing to replace.
        if (options.Level != MapInkLevel.Graphical)
            markup = ReplaceStylesheet(markup, BuildStylesheet(options));

        return ApplyRootOpacity(markup, options.Opacity);
    }

    /// <summary>
    /// The generated stylesheet. Declarations are marked important because a handful of shapes
    /// carry inline styles, and an inline style beats a plain class rule — without this, a few
    /// buildings would stay opaque while the rest of the map faded, which looks like a bug.
    /// </summary>
    public static string BuildStylesheet(MapInkOptions o)
    {
        var css = new StringBuilder();

        css.AppendLine("/* Generated by RatNav — map ink. */");

        // Drop-shadow filters over live gameplay are pure cost: they blur the one thing that
        // has to stay crisp, and they are the most expensive part of the SVG to composite.
        css.AppendLine(".shadow { filter: none !important; }");

        switch (o.Level)
        {
            // Full and Structure differ in one thing: whether the ground is still ground. Full
            // keeps it, which reads better on a screen of its own; Structure drops it to a
            // whisper, which is what stops a map burying the game underneath it.
            case MapInkLevel.Full:
            case MapInkLevel.Structure:
                css.AppendLine($$"""
                    {{TerrainSelectors}} {
                      fill: {{o.TerrainColor}} !important;
                      fill-opacity: {{F(o.Level == MapInkLevel.Full ? 0.45 : o.TerrainOpacity)}} !important;
                      stroke: none !important;
                    }
                    {{StructureSelectors}} {
                      fill: {{o.Accent}} !important;
                      fill-opacity: 0.18 !important;
                      stroke: {{o.Accent}} !important;
                      stroke-width: 1 !important;
                      stroke-opacity: 0.9 !important;
                    }
                    {{BoundarySelectors}} {
                      fill: none !important;
                      stroke: {{o.Accent}} !important;
                      stroke-opacity: 0.75 !important;
                    }
                    {{RouteSelectors}} {
                      fill: none !important;
                      stroke: {{o.RouteColor}} !important;
                      stroke-opacity: 0.8 !important;
                    }
                    {{DetailSelectors}} {
                      fill: {{o.RouteColor}} !important;
                      fill-opacity: 0.9 !important;
                    }
                    """);
                break;

            case MapInkLevel.Outline:
                css.AppendLine($$"""
                    {{TerrainSelectors}} {
                      display: none !important;
                    }
                    {{StructureSelectors}} {
                      fill: none !important;
                      stroke: {{o.Accent}} !important;
                      stroke-width: 1.25 !important;
                      stroke-opacity: 0.95 !important;
                    }
                    {{BoundarySelectors}} {
                      fill: none !important;
                      stroke: {{o.Accent}} !important;
                      stroke-opacity: 0.6 !important;
                    }
                    {{RouteSelectors}} {
                      fill: none !important;
                      stroke: {{o.RouteColor}} !important;
                      stroke-opacity: 0.55 !important;
                    }
                    {{DetailSelectors}} {
                      display: none !important;
                    }
                    """);
                break;
        }

        css.AppendLine(o.ShowHazards
            ? $"{HazardSelectors} {{ stroke-opacity: 0.85 !important; fill-opacity: 0.15 !important; }}"
            : $"{HazardSelectors} {{ display: none !important; }}");

        if (o.Halo)
        {
            // One filter on the root, rather than per-shape strokes: same legibility, a
            // fraction of the compositing cost.
            css.AppendLine("svg > g { filter: drop-shadow(0 0 1.2px rgba(0,0,0,0.9)); }");
        }

        return css.ToString();
    }

    /// <summary>
    /// Swaps the map's own stylesheet for ours. If a map has no stylesheet, ours is injected
    /// after the opening tag instead.
    /// </summary>
    private static string ReplaceStylesheet(string markup, string css)
    {
        var styleBlock = $"<style id=\"ratnav_ink\">{css}</style>";

        if (StyleElement().IsMatch(markup))
            return StyleElement().Replace(markup, styleBlock, 1);

        return SvgOpenTag().Replace(markup, m => m.Value + styleBlock, 1);
    }

    private static string ApplyRootOpacity(string markup, double opacity)
    {
        var clamped = Math.Clamp(opacity, 0.0, 1.0);

        return SvgOpenTag().Replace(
            markup,
            m => m.Value.TrimEnd('>') + $" opacity=\"{F(clamped)}\">",
            1);
    }

    private static string F(double value) =>
        value.ToString("0.###", System.Globalization.CultureInfo.InvariantCulture);

    [GeneratedRegex("<style\\b[^>]*>.*?</style>", RegexOptions.Singleline | RegexOptions.IgnoreCase)]
    private static partial Regex StyleElement();

    [GeneratedRegex("<svg\\b[^>]*>", RegexOptions.IgnoreCase)]
    private static partial Regex SvgOpenTag();
}
